[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "alfalfa_lvgl"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
keywords = []
authors = [
  { name = "Ricardo Marchesan", email = "ricardo@azevem.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "alfalfa",
]

[project.urls]
Documentation = "https://github.com/rikardonm/alfalfa_lvgl#readme"
Issues = "https://github.com/rikardonm/alfalfa_lvgl/issues"
Source = "https://github.com/rikardonm/alfalfa_lvgl"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build]
packages = ["src/alfalfa"]

[tool.hatch.build.hooks.vcs]
version-file = "src/alfalfa/lvgl/version.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/alfalfa/lvgl tests}"

[tool.coverage.run]
source_pkgs = ["alfalfa_lvgl", "tests"]
branch = true
parallel = true
omit = [
  "src/alfalfa/lvgl/version.py",
]

[tool.coverage.paths]
alfalfa_lvgl = ["src/alfalfa/lvgl", "*/alfalfa/lvgl/src/alfalfa/lvgl"]
tests = ["tests", "*/alfalfa/lvgl/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.black]
line-length = 120
target-version = ['py312']

[tool.flake8]
max-line-length = 120
